module.exports = {
    login: 'programacionparaaprender',
    id: 8290696,
    node_id: 'MDQ6VXNlcjgyOTA2OTY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8290696?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/programacionparaaprender',
    html_url: 'https://github.com/programacionparaaprender',
    followers_url: 'https://api.github.com/users/programacionparaaprender/followers',
    following_url: 'https://api.github.com/users/programacionparaaprender/following{/other_user}',        
    gists_url: 'https://api.github.com/users/programacionparaaprender/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/programacionparaaprender/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/programacionparaaprender/subscriptions',
    organizations_url: 'https://api.github.com/users/programacionparaaprender/orgs',
    repos_url: 'https://api.github.com/users/programacionparaaprender/repos',
    events_url: 'https://api.github.com/users/programacionparaaprender/events{/privacy}',
    received_events_url: 'https://api.github.com/users/programacionparaaprender/received_events',
    type: 'User',
    site_admin: false,
    name: 'Programación para aprender',
    company: null,
    public_repos: 132,
    public_gists: 0,
    followers: 11,
    following: 24,
    created_at: '2014-07-28T15:02:44Z',
    updated_at: '2023-01-10T14:39:57Z'
  };